server:
  port: 8092
  servlet:
    context-path: /elasticsearch

#   db configs
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/sugea
    username: root
    password: root
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: false


# elsaticsearch configs
  elasticsearch:
#    uris: http://localhost:9200
#    uris: https://vvaoul96ry.loclx.io/ #with localXpose
#    username: elastic
#    password: changeme
#    password: QF0D4oc3ndC+_Ze_Ryk-

  