server:
  port: 8092
  servlet:
    context-path: /elasticsearch

#   db configs
spring:
  datasource:
    url: jdbc:mysql://localhost/sugea
    username: <user>
    password: <pass>
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true


# elsaticsearch configs
  elasticsearch:
    uris: http://localhost:9200

  